language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-24

env:
    global:
    - TERM=dumb

script: ./gradlew lintDebug testDebug :LeBlue-java:test

after_success:
    - ./gradlew jacocoTestReport
    - bash <(curl -s https://codecov.io/bash)