language: java

env:
    global:
    - TERM=dumb

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect

script: ./gradlew lintDefaultFlavorDebug testDefaultFlavorDebug

after_success:
    - ./gradlew jacocoTestReport
    - ./gradlew coveralls
