language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3

env:
    global:
    - TERM=dumb

script: ./gradlew lintDefaultFlavorDebug testDefaultFlavorDebug

after_success:
    - ./gradlew jacocoTestReport
    - ./gradlew coveralls
